USE NHL_PredictDB;

-- INSERTS PLAYOFFS NHL

-- Playoffs 2021-2022
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2021-2022'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'FLA'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'WSH'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'FLA'), 4, 2);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2021-2022'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'TOR'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'TBL'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'TBL'), 3, 4);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2021-2022'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'CAR'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'BOS'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'CAR'), 4, 3);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2021-2022'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'NYR'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'PIT'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'NYR'), 4, 3);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2021-2022'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'COL'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'NSH'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'COL'), 4, 0);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2021-2022'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'MIN'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'STL'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'STL'), 2, 4);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2021-2022'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'CGY'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'DAL'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'CGY'), 4, 3);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2021-2022'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'EDM'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'LAK'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'EDM'), 4, 3);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2021-2022'), '2nd Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'FLA'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'TBL'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'TBL'), 0, 4);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2021-2022'), '2nd Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'CAR'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'NYR'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'NYR'), 3, 4);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2021-2022'), '2nd Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'COL'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'STL'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'COL'), 4, 2);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2021-2022'), '2nd Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'CGY'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'EDM'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'EDM'), 1, 4);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2021-2022'), 'Eastern Conference Finals', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'NYR'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'TBL'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'TBL'), 2, 4);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2021-2022'), 'Western Conference Finals', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'COL'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'EDM'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'COL'), 4, 0);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2021-2022'), 'Stanley Cup Final', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'COL'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'TBL'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'COL'), 4, 2);

-- Playoffs 2022-2023
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2022-2023'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'BOS'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'FLA'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'FLA'), 3, 4);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2022-2023'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'TOR'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'TBL'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'TOR'), 4, 2);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2022-2023'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'CAR'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'NYI'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'CAR'), 4, 2);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2022-2023'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'NJD'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'NYR'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'NJD'), 4, 3);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2022-2023'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'COL'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'SEA'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'SEA'), 3, 4);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2022-2023'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'DAL'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'MIN'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'DAL'), 4, 2);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2022-2023'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'VGK'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'WPG'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'VGK'), 4, 1);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2022-2023'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'EDM'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'LAK'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'EDM'), 4, 2);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2022-2023'), '2nd Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'TOR'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'FLA'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'FLA'), 1, 4);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2022-2023'), '2nd Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'CAR'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'NJD'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'CAR'), 4, 1);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2022-2023'), '2nd Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'DAL'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'SEA'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'DAL'), 4, 3);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2022-2023'), '2nd Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'VGK'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'EDM'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'VGK'), 4, 2);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2022-2023'), 'Eastern Conference Finals', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'CAR'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'FLA'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'FLA'), 0, 4);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2022-2023'), 'Western Conference Finals', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'VGK'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'DAL'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'VGK'), 4, 2);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2022-2023'), 'Stanley Cup Final', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'VGK'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'FLA'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'VGK'), 4, 1);

-- Playoffs 2023-2024
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2023-2024'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'FLA'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'TBL'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'FLA'), 4, 1);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2023-2024'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'BOS'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'TOR'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'BOS'), 4, 3);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2023-2024'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'NYR'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'WSH'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'NYR'), 4, 0);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2023-2024'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'CAR'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'NYI'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'CAR'), 4, 1);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2023-2024'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'DAL'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'VGK'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'DAL'), 4, 3);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2023-2024'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'WPG'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'COL'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'COL'), 1, 4);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2023-2024'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'VAN'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'NSH'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'VAN'), 4, 2);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2023-2024'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'EDM'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'LAK'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'EDM'), 4, 1);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2023-2024'), '2nd Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'FLA'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'BOS'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'FLA'), 4, 2);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2023-2024'), '2nd Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'NYR'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'CAR'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'NYR'), 4, 2);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2023-2024'), '2nd Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'DAL'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'COL'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'DAL'), 4, 2);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2023-2024'), '2nd Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'VAN'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'EDM'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'EDM'), 3, 4);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2023-2024'), 'Eastern Conference Finals', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'NYR'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'FLA'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'FLA'), 2, 4);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2023-2024'), 'Western Conference Finals', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'DAL'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'EDM'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'EDM'), 2, 4);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2023-2024'), 'Stanley Cup Final', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'FLA'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'EDM'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'FLA'), 4, 3);

-- Playoffs 2024-2025
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2024-2025'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'TOR'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'OTT'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'TOR'), 4, 2);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2024-2025'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'TBL'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'FLA'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'FLA'), 1, 4);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2024-2025'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'WSH'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'MTL'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'WSH'), 4, 1);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2024-2025'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'CAR'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'NJD'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'CAR'), 4, 1);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2024-2025'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'WPG'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'STL'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'WPG'), 4, 3);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2024-2025'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'DAL'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'COL'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'DAL'), 4, 3);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2024-2025'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'VGK'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'MIN'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'VGK'), 4, 2);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2024-2025'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'LAK'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'EDM'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'EDM'), 2, 4);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2024-2025'), '2nd Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'TOR'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'FLA'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'FLA'), 3, 4);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2024-2025'), '2nd Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'WSH'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'CAR'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'CAR'), 1, 4);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2024-2025'), '2nd Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'WPG'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'DAL'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'DAL'), 2, 4);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2024-2025'), '2nd Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'VGK'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'EDM'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'EDM'), 1, 4);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2024-2025'), 'Eastern Conference Finals', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'CAR'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'FLA'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'FLA'), 1, 4);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2024-2025'), 'Western Conference Finals', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'DAL'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'EDM'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'EDM'), 1, 4);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2024-2025'), 'Stanley Cup Final', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'EDM'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'FLA'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'FLA'), 2, 4);

-- Playoffs 2025-2026
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2025-2026'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'BUF'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'BOS'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'BUF'), 4, 2);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2025-2026'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'TBL'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'MTL'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'MTL'), 3, 4);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2025-2026'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'CAR'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'OTT'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'CAR'), 4, 0);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2025-2026'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'PIT'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'PHI'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'PHI'), 2, 4);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2025-2026'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'COL'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'LAK'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'COL'), 4, 0);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2025-2026'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'DAL'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'MIN'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'MIN'), 2, 4);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2025-2026'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'VGK'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'UTA'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'VGK'), 4, 2);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2025-2026'), '1st Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'EDM'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'ANA'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'ANA'), 2, 4);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2025-2026'), '2nd Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'BUF'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'MTL'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'MTL'), 3, 4);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2025-2026'), '2nd Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'CAR'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'PHI'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'CAR'), 4, 0);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2025-2026'), '2nd Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'COL'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'MIN'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'COL'), 4, 1);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2025-2026'), '2nd Round', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'VGK'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'ANA'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'VGK'), 4, 2);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2025-2026'), 'Eastern Conference Finals', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'CAR'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'MTL'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'CAR'), 4, 1);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2025-2026'), 'Western Conference Finals', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'COL'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'VGK'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'VGK'), 0, 4);
INSERT INTO Playoffs (TemporadaID, Ronda, Equipo_Local, Equipo_Visitante, Ganador, Juegos_Local, Juegos_Visitante) VALUES ((SELECT TemporadaID FROM Temporadas WHERE Nombre_Temporada = '2025-2026'), 'Stanley Cup Final', (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'CAR'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = 'VGK'), (SELECT EquipoID FROM Equipos WHERE Abreviacion = NULL), 0, 0);

SELECT COUNT(*) AS Total_Playoffs
FROM Playoffs;